
services:
    chatterbox_tts:
      build: 
        context: .
        args:
          OUTPUT_DIR: /app/outputs
          DEBUG: ${DEBUG:-no}
      ports:
        - "${PORT:-9080}:9080"
      volumes:
        - ./outputs:/app/outputs
        - ./src:/app/src
        - ./voices:/app/src/voices
      container_name: chatterbox-tts-service
      
